spring:
  application:
    name: time
  profiles:
    active: local

  config:
    import:
      - optional:classpath:wakatime.yml
      - optional:classpath:swagger.yml
      - optional:classpath:batch.yml

access-token:
  publishing:
    size: 50